Corrigé des tags de skip pour github qui ont été perdus après un gros…
epfl-dojo/ansiblePI pull request #26
Opened 2020-04-23 16:30 UTC by zuzu59

… merge

2020-04-23 19:45 UTC, ponsfrilus commented on LICENSE
> +MIT License
Bonne idée d'avoir mis une licence, mais tous les plays des rôles ont une license BSD (par exemple https://github.com/epfl-dojo/ansiblePI/tree/master/roles/comfort). Bien que les deux licenses soient permissivent (c.f. https://en.wikipedia.org/wiki/License_compatibility), je pense que l'idéal serait d'avoir la même partout.

2020-04-23 19:46 UTC, ponsfrilus commented on LICENSE
> +Copyright (c) 2018 strikerpt
strikerpt = hugo

2020-04-23 19:47 UTC, ponsfrilus requested changes
IMHO license have to be changed.

2020-04-24 07:09 UTC, zuzu59 commented on LICENSE
> +Copyright (c) 2018 strikerpt
merde j'ai oublié ce coup :-(

2020-04-24 08:31 UTC, ponsfrilus approved these changes
Okay, let's roll!

2020-04-29 12:09 UTC, merged